<?php

/**
 * Created by PhpStorm.
 * User: shenyang
 * Date: 2018/6/4
 * Time: 下午4:44
 */

namespace app\common\managers;

use Illuminate\Support\Collection;

class ModelExpansionManager extends Collection
{
    public function get($key, $default = null)
    {
        if(!$this->has($key)){
            $this->put($key,collect());
        }

        return parent::get($key, $default); // TODO: Change the autogenerated stub
    }
}