<?php
/**
 * Created by PhpStorm.
 * Author: 芸众商城 www.yunzshop.com
 * Date: 2017/2/22
 * Time: 下午1:51
 */

namespace app\backend\modules\goods\controllers;

use app\backend\modules\goods\models\Brand;
use app\backend\modules\goods\models\Category;
use app\backend\modules\goods\models\Goods;
use app\backend\modules\goods\models\GoodsOption;
use app\backend\modules\goods\models\GoodsSpecItem;
use app\backend\modules\goods\models\Sale;
use app\backend\modules\goods\services\CopyGoodsService;
use app\backend\modules\goods\services\CreateGoodsService;
use app\backend\modules\goods\services\EditGoodsService;
use app\backend\modules\goods\services\GoodsOptionService;
use app\backend\modules\goods\services\GoodsService;
use app\common\components\BaseController;
use app\backend\modules\goods\services\CategoryService;
use app\backend\modules\goods\models\GoodsParam;
use app\backend\modules\goods\models\GoodsSpec;
use app\common\components\Widget;
use app\common\helpers\Cache;
use app\common\helpers\PaginationHelper;
use app\common\helpers\Url;
use app\common\models\GoodsCategory;
use Setting;
use app\common\services\goods\VideoDemandCourseGoods;
use app\common\models\Store as StoreCashier;
use Yunshop\Designer\models\Store;
use Yunshop\Hotel\common\models\Hotel;
use Yunshop\LeaseToy\models\LeaseOrderModel;
use Yunshop\LeaseToy\models\LeaseToyGoodsModel;
use Yunshop\VideoDemand\models\CourseGoodsModel;
use app\common\helpers\ImageHelper;


class GoodsController extends BaseController
{
    protected $goods_id = null;
    protected $shopset;
    protected $shoppay;
    private $list;
    private $brand;
    //private $goods;
    protected $lang = null;

    protected $success_url = 'goods.goods.index';


    public function preAction()
    {
        parent::preAction(); // TODO: Change the autogenerated stub
        $this->lang = array(
            "shopname" => "商品名称",
            "mainimg" => "商品图片",
            "limittime" => "限时卖时间",
            "shopnumber" => "商品编号",
            "shopprice" => "商品价格",
            "putaway" => "上架",
            "soldout" => "下架",
            "good" => "商品",
            "price" => "价格",
            'yes_stock' => '出售中',
            'no_stock' => '售罄',
            "repertory" => "库存",
            "copyshop" => "复制商品",
            "isputaway" => "是否上架",
            "shopdesc" => "商品描述",
            "shopinfo" => "商品详情",
            'shopoption' => "商品规格",
            'marketprice' => "销售价格",
            'shopsubmit' => "发布商品"
        );
        $this->goods_id = (int)\YunShop::request()->id;
        $this->shopset = Setting::get('shop.category');
    }

    public function index()
    {
        return view('goods.index', ['data' => json_encode($this->goodsListData())]);
    }


    public function goodsSearch()
    {
        //课程商品id集合
        $courseGoods_ids = (new VideoDemandCourseGoods())->courseGoodsIds();

        $requestSearch = request()->search;
        $page = request()->page;
        if ($requestSearch) {
            $requestSearch = array_filter($requestSearch, function ($item) {
                return $item !== '';// && $item !== 0;
            });

            $categorySearch = array_filter(request()->category, function ($item) {
                if (is_array($item)) {
                    return !empty($item[0]);
                }
                return !empty($item);
            });

            if ($categorySearch) {
                $requestSearch['category'] = $categorySearch;
            }
        }

        $list = Goods::Search($requestSearch)->pluginIdShow()->orderBy('display_order', 'desc')->orderBy('yz_goods.id', 'desc')->paginate(20);
        PaginationHelper::show($list->total(), $list->currentPage(), $list->perPage());
        foreach ($list as $key => $item) {
            $list[$key]['thumb'] = yz_tomedia($item->thumb);
            if (in_array($item['id'], $courseGoods_ids)) {
                $list[$key]['link'] = yzAppFullUrl('member/coursedetail/' . $item['id']);
            } else {
                $list[$key]['link'] = yzAppFullUrl('goods/' . $item['id']);
            }

        }

        if ($list) {
            return $this->successJson('成功', $list);
        } else {
            return $this->errorJson('找不到数据');
        }

    }

    private function goodsListData()
    {
        //课程商品id集合
        $courseGoods_ids = (new VideoDemandCourseGoods())->courseGoodsIds();

        //增加商品属性搜索
        $product_attr_list = [
            'is_new' => '新品',
            'is_hot' => '热卖',
            'is_recommand' => '推荐',
            'is_discount' => '促销',
        ];

        $brands = Brand::getBrands()->getQuery()->select(['id','name'])->get()->toArray();

        $requestSearch = \YunShop::request()->search;
        if ($requestSearch) {
            $requestSearch = array_filter($requestSearch, function ($item) {
                return $item !== '';// && $item !== 0;
            });

            $categorySearch = array_filter(\YunShop::request()->category, function ($item) {
                if (is_array($item)) {
                    return !empty($item[0]);
                }
                return !empty($item);
            });

            if ($categorySearch) {
                $requestSearch['category'] = $categorySearch;
            }
        }
//        $catetory_menus = CategoryService::getCategoryMenu(
//            [
//                'catlevel' => $this->shopset['cat_level'],
//                'ids'   => isset($categorySearch) ? array_values($categorySearch) : [],
//            ]
//        );

//        $catetory_menus = CategoryService::getCategoryMultiMenuSearch(
//            [
//                'catlevel' => $this->shopset['cat_level'],
//                'ids'   => isset($categorySearch) ? array_values($categorySearch) : [],
//            ]
//        );

        $catetory_menus = [
            'catlevel' => $this->shopset['cat_level'],
            'ids' => Category::getAllCategoryGroupArray()//CategoryFactory::create('shop'),
        ];

        $list = Goods::select(['id','display_order','thumb','title','has_option','price','stock','real_sales','status','is_hot','is_new','is_recommand','is_discount'])->Search($requestSearch)->pluginIdShow()->orderBy('display_order', 'desc')->orderBy('yz_goods.id', 'desc')->paginate(20);
        foreach ($list as $key => $item) {
            $list[$key]['thumb'] = yz_tomedia($item->thumb);

            if (in_array($item['id'], $courseGoods_ids)) {
                $list[$key]['link'] = yzAppFullUrl('member/coursedetail/' . $item['id']);
            } else {
                $list[$key]['link'] = yzAppFullUrl('goods/' . $item['id']);
            }

        }

        //$pager = PaginationHelper::show($list->total(), $list->currentPage(), $list->perPage());


        $edit_url = 'goods.goods.edit';
        $delete_url = 'goods.goods.destroy';
        $delete_msg = '确认删除此商品？';
        $sort_url = 'goods.goods.displayorder';


        $data = [
            'list' => $list,
            //课程商品id
            'courseGoods_ids' => $courseGoods_ids,
            //'status' => $status,
            'brands' => $brands,
            'requestSearch' => $requestSearch,
            'catetory_menus' => $catetory_menus,
            'lang' => $this->lang,
            'product_attr_list' => $product_attr_list,
            'yz_url' => 'yzWebUrl',
            'edit_url' => $edit_url,
            'delete_url' => $delete_url,
            'delete_msg' => $delete_msg,
            'sort_url' => $sort_url,
            'product_attr' => $requestSearch['product_attr'],
            'copy_url' => 'goods.goods.copy',
        ];
        return $data;
    }

    /**
     * 商品列表页数据
     */
    public function goodsList()
    {

        return $this->successJson('成功', $this->goodsListData());
    }

    public function copy()
    {
        $id = intval(\YunShop::request()->id);
        if (!$id) {
            $this->error('请传入正确参数.');
        }

        $result = CopyGoodsService::copyGoods($id);
        if (!$result) {
            $this->error('商品不存在.');
        }
        return $this->message('商品复制成功', Url::absoluteWeb($this->success_url));
    }

    public function create()
    {
        $request = Request();
        $goods_service = new CreateGoodsService($request);
        $result = $goods_service->create();

        if (isset($goods_service->error)) {
            $this->error($goods_service->error);
        }

        if ($result['status'] == 1) {
            Cache::flush();
            return $this->message('商品创建成功', Url::absoluteWeb($this->success_url));
        } else if ($result['status'] == -1) {
            if (isset($result['msg'])) {
                $this->error($result['msg']);
            }

            !session()->has('flash_notification.message') && $this->error('商品修改失败');
        }
        return view('goods.goods', [
            'goods' => $goods_service->goods_model,
            'lang' => $this->lang,
            'params' => $goods_service->params->toArray(),
            'brands' => $goods_service->brands->toArray(),
            'allspecs' => [],
            'html' => '',
            'var' => \YunShop::app()->get(),
            'catetory_menus' => $goods_service->catetory_menus,
            'virtual_types' => [],
            'shopset' => $this->shopset
        ])->render();
    }

    public function edit()
    {
        /*$this->goods_id = intval(\YunShop::request()->id);

        if (!$this->goods_id){
            $this->message('请传入正确参数.');
        }

        $requestGoods = \YunShop::request()->goods;
        $goodsModel = Goods::with('hasManyParams')->with('hasManySpecs')->with('hasManyGoodsCategory')->find($this->goods_id);//->getGoodsById(2);
        //dd($goodsModel->hasManyGoodsCategory->toArray());

        //获取规格名及规格项
        foreach ($goodsModel->hasManySpecs as &$spec) {
            $spec['items'] = GoodsSpecItem::where('specid', $spec['id'])->get()->toArray();
        }

        //获取具体规格内容html
        $optionsHtml = GoodsOptionService::getOptions($this->goods_id, $goodsModel->hasManySpecs);

        //商品其它图片反序列化
        $goodsModel->thumb_url = !empty($goodsModel->thumb_url) ? unserialize($goodsModel->thumb_url) : [];
        //$goodsModel->piclist = !empty($goodsModel->thumb_url) ? $goodsModel->thumb_url : [];


        //$catetorys = Category::getAllCategoryGroup();
        if ($requestGoods) {

            $requestGoods['has_option'] = $requestGoods['has_option'] ? $requestGoods['has_option'] : 0;
            if ($requestGoods['has_option'] && !\YunShop::request()['option_ids']) {
                $requestGoods['has_option'] = 0;
                //return $this->message('启用商品规格，必须添加规格项等信息', Url::absoluteWeb('goods.goods.index'));
            }
            //将数据赋值到model
            $requestGoods['thumb'] = tomedia($requestGoods['thumb']);

            if(isset($requestGoods['thumb_url'])){
                $requestGoods['thumb_url'] = serialize(
                    array_map(function($item){
                        return tomedia($item);
                    }, $requestGoods['thumb_url'])
                );
            }

            $category_model = GoodsCategory::where("goods_id", $goodsModel->id)->first();
            if (!empty($category_model)) {
                $category_model->delete();
            }
            GoodsService::saveGoodsCategory($goodsModel, \YunShop::request()->category, $this->shopset);

            $goodsModel->setRawAttributes($requestGoods);
            $goodsModel->widgets = \YunShop::request()->widgets;
            //其他字段赋值
            $goodsModel->uniacid = \YunShop::app()->uniacid;
            $goodsModel->id = $this->goods_id;
            $validator = $goodsModel->validator($goodsModel->getAttributes());
            if ($validator->fails()) {
                $this->error($validator->messages());
            } else {
                //数据保存
                if ($goodsModel->save()) {
                    GoodsParam::saveParam(\YunShop::request(), $goodsModel->id, \YunShop::app()->uniacid);
                    GoodsSpec::saveSpec(\YunShop::request(), $goodsModel->id, \YunShop::app()->uniacid);
                    GoodsOption::saveOption(\YunShop::request(), $goodsModel->id, GoodsSpec::$spec_items, \YunShop::app()->uniacid);
                    //显示信息并跳转
                    return $this->message('商品修改成功', Url::absoluteWeb('goods.goods.index'));
                } else {
                    !session()->has('flash_notification.message') && $this->error('商品修改失败');
                    //$this->error('商品修改失败');
                }
            }

        }

        $brands = Brand::getBrands()->get();

        //dd($goods_categorys);
        $catetory_menus = '';
        if (isset($goodsModel->hasManyGoodsCategory[0])){
            foreach($goods_categorys = $goodsModel->hasManyGoodsCategory->toArray() as $goods_category){
                $catetory_menus = CategoryService::getCategoryMenu(['catlevel' => $this->shopset['cat_level'], 'ids' => explode(",", $goods_category['category_ids'])]);
            }
        }*/
//        dump(\\app\common\modules\widget\Widget::current()->getItem('goods'));
        //todo 所有操作去service里进行，供应商共用此方法。
        $request = Request();
        $goods_service = new EditGoodsService($request->id, \YunShop::request());

        $result = $goods_service->edit();
        /*
        $type2 = \YunShop::request()->goods['type2'];
        $goods = \app\common\models\Goods::find($this->goods_id);
        $plugin_id = '';
        if (app('plugins')->isEnabled('lease-toy')) {
            $LeaseToyGoods = LeaseToyGoodsModel::ofGoodsId($this->goods_id)->first();
            $plugin_id = LeaseOrderModel::PLUGIN_ID;
            if ($type2) {
                if ($type2 != '2') {
                    $goods->plugin_id =  0;
                    $LeaseToyGoods->is_lease = 0;
                    $goods->save();
                } else if($type2 == '2') {
                    $goods->plugin_id =  $plugin_id;
                    $goods->type2 =  $type2;
                    $LeaseToyGoods->is_lease = '1';
                }
                $LeaseToyGoods->save();
                $goods->save();
            }
        }
        //!app('plugins')->isEnabled('lease-toy') && $goods->type2 == '2' ||
        if (!app('plugins')->isEnabled('video-demand') && $goods->type2 == '3') {
            Setting::set('shop.goods.type2', $goods->type2);
            $goods->type2 = '1';
            $goods->save();
        } else if (app('plugins')->isEnabled('video-demand')) {
            $item = CourseGoodsModel::getModel($this->goods_id,'');
            if (Setting::get('shop.goods.type2') == '3') {
                $goods->type2 = Setting::get('shop.goods.type2');
                Setting::set('shop.goods.type2', '');
            }
            if ($item->is_course == '1') {
                $goods->type2 =  '3';
            }
            $goods->save();
        }
    */
        if ($result['status'] == 1) {
            Cache::flush();
            return $this->message('商品修改成功', Url::absoluteWeb($this->success_url));
        } else if ($result['status'] == -1) {
            if (isset($result['msg'])) {
                $this->error($result['msg']);
            }
            !session()->has('flash_notification.message') && $this->error('商品修改失败');
        }
        return view('goods.goods', [
            'goods' => $goods_service->goods_model,
            'lang' => $this->lang,
            'goods_video' => collect($goods_service->goods_model->hasOneGoodsVideo)->toArray(),
            'params' => collect($goods_service->goods_model->hasManyParams)->toArray(),
            'allspecs' => collect($goods_service->goods_model->hasManySpecs)->toArray(),
            'html' => $goods_service->optionsHtml,
            'var' => \YunShop::app()->get(),
            'brands' => $goods_service->brands,
            'catetory_menus' => implode('', $goods_service->catetory_menus),
            'virtual_types' => [],
            'shopset' => $this->shopset,
            'type' => 'edit',
        ])->render();
    }

    public function qrcode()
    {

        //$this->error($goods);
    }

    // public function displayorder()
    // {
    //     $displayOrders = request()->display_order;
    //     foreach($displayOrders as $id => $displayOrder){
    //         $goods = \app\common\models\Goods::find($id);
    //         $goods->display_order = $displayOrder;
    //         $goods->save();
    //     }
    //     // return $this->message('商品排序成功', Url::absoluteWeb($this->success_url));
    //     return $this->successJson('排序成功');
    //     //$this->error($goods);
    // }


    public function displayorder()
    {
        $id = request()->id;
        $value = request()->value;

        if (empty($id)) {
            return $this->errorJson('排序失败,商品ID不能为空');
        }

        $goods = \app\common\models\Goods::find($id);
        $goods->display_order = $value;
        if ($goods->save()) {
            return $this->successJson('排序成功');
        } else {
            return $this->errorJson('排序失败');
        }
        // return $this->message('商品排序成功', Url::absoluteWeb($this->success_url));

        //$this->error($goods);
    }

    public function change()
    {
        //dd(\YunShop::request());
        $id = request()->id;
        $field = request()->type;
        $goods = \app\common\models\Goods::find($id);

        if ($field == 'price') {
            $sale = Sale::getList($goods->id);
            /*
                        if (!empty($sale->max_point_deduct)
                            && $sale->max_point_deduct > \YunShop::request()->value) {
                            echo json_encode(['status' => -1, 'msg' => '积分抵扣金额大于商品价格']);
                            exit;
                        }
            */
        }

        $goods->$field = request()->value;
        if ($goods->save()) {
            return $this->successJson('修改成功');
        } else {
            return $this->errorJson('修改失败');
        }

        //$this->error($goods);
    }

    /**
     * 商品上下架权限需要独立控制 Yi_190517
     */
    public function setPutaway()
    {
        return $this->setProperty();
    }

    public function setProperty()
    {
        $id = request()->id;
        $field = request()->type;
        $data = request()->data; //(request()->data == 1 ? '0' : '1');
        $goods = \app\common\models\Goods::find($id);
        $goods->$field = $data;
        //dd($goods);
        $goods->save();
        Cache::flush();
        echo json_encode(["data" => $data, "result" => 1]);
    }

    //批量上下架
    public function batchSetProperty()
    {
        $ids = request()->ids;
        $data = request()->data;
        foreach ($ids as $id) {
            $goods = \app\common\models\Goods::find($id);
            $goods->status = $data;
            $goods->save();
        }
        echo json_encode(["data" => $data, "result" => 1]);
    }

    public function destroy()
    {
        $id = request()->id;
        $goods = Goods::destroy($id);
        return $this->successJson('商品删除成功');
    }

    public function batchDestroy()
    {
        $ids = request()->ids;
        foreach ($ids as $id) {
            $goods = Goods::destroy($id);
        }
        echo json_encode([
            "result" => $goods,
        ]);
    }

    /**
     * 获取参数模板
     */
    public function getParamTpl()
    {
        $tag = random(32);
        return view('goods.tpl.param', [
            'tag' => $tag,
        ])->render();
        //include $this->template('web/shop/tpl/param');
    }

    /**
     * 获取规格模板
     */
    public function getSpecTpl()
    {
        $spec = array(
            "id" => random(32),
            "title" => '',
            'items' => [
                /*"id" => random(32),
                "title" => 'test',
                "show" => 1*/
            ],
        );
        return view('goods/tpl/spec', [
            'spec' => $spec,
        ])->render();
    }

    /**
     * 获取规格项模板
     */
    public function getSpecItemTpl()
    {
        $goodsModel = Goods::find($this->goods_id);

        $spec = array(
            "id" => \YunShop::request()->specid,
        );

        $specitem = array(
            "id" => random(32),
            "title" => \YunShop::request()->title,
            "show" => 1,
            'virtual' => '',
            'title2' => '',
            'thumb' => '',
        );

        return view('goods/tpl/spec_item', [
            'spec' => $spec,
            'goods' => $goodsModel,
            'specitem' => $specitem,
        ])->render();
    }

    /**
     * 获取搜索商品
     * @return html
     */
    public function getSearchGoods()
    {
        $keyword = \YunShop::request()->keyword;
        $goods = Goods::select('id', 'title', 'thumb')
            ->where('title', 'like', '%' . $keyword . '%')
            ->where('status', 1)
            ->whereInPluginIds()
            ->get();

        if (!$goods->isEmpty()) {
            $goods = set_medias($goods->toArray(), array('thumb', 'share_icon'));
        
        }
        return view('goods.query', [
            'goods' => $goods,
            'exchange' => \YunShop::request()->exchange,
        ])->render();

    }

    public function getSearchGoodsLevel()
    {
        $keyword = \YunShop::request()->keyword;
        $goods = \app\common\models\Goods::select('id', 'title', 'thumb')
            ->where('title', 'like', '%' . $keyword . '%')
            ->where('status', 1)
            ->whereIn('is_plugin', ['0','1'])
            ->whereIn('plugin_id', ['0','32','92'])
            ->get();
        if (!$goods->isEmpty()) {
            $goods = set_medias($goods->toArray(), array('thumb', 'share_icon'));
        }
        return view('goods.query', [
            'goods' => $goods,
            'exchange' => \YunShop::request()->exchange,
        ])->render();

    }

    /**
     * 获取搜索门店
     * @return html
     */
    public function getSearchStore()
    {
        $keyword = \YunShop::request()->keyword;
        $store = StoreCashier::getStoreByName($keyword);
        return view('goods.store', [
            'store' => $store
        ])->render();

    }

    /**
     * 获取搜索酒店
     * @return html
     */
    public function getSearchHotel()
    {
        if (app('plugins')->isEnabled('hotel')) {
            $keyword = \YunShop::request()->keyword;
            $hotel = Hotel::getHotelByName($keyword);
            return view('goods.hotel', [
                'hotel' => $hotel
            ])->render();

        }
    }

    /**
     * 获取搜索商品by经销商
     * @return html
     */
    public function getSearchGoodsByDividend()
    {
        $keyword = \YunShop::request()->keyword;
        $goods = Goods::getGoodsByName($keyword);
        if (!$goods->isEmpty()) {
            $goods = set_medias($goods->toArray(), array('thumb', 'share_icon'));
        }
        return view('goods.dividend_goods_query', [
            'goods' => $goods
        ])->render();

    }

    public function getSearchGoodsByDividendLevel()
    {
        $keyword = \YunShop::request()->keyword;
        $goods = \app\common\models\Goods::getGoodsLevelByName($keyword);
        if (!$goods->isEmpty()) {
            $goods = set_medias($goods->toArray(), array('thumb', 'share_icon'));
        }
        return view('goods.dividend_goods_query', [
            'goods' => $goods
        ])->render();

    }

    public function getMyLinkGoods()
    {
        if (!\YunShop::request()->kw) {
            $postData = file_get_contents('php://input', true);
            $obj = json_decode($postData);
            \YunShop::request()->kw = $obj->kw;
            //dd($obj->kw);
        }

        if (\YunShop::request()->kw) {
            $goods = \app\common\models\Goods::getGoodsByName(\YunShop::request()->kw);

            if (!$goods->isEmpty()) {
                $goods = set_medias($goods->toArray(), array('thumb', 'share_icon'));
            }
            $goods = collect($goods)->map(function ($item) {

                $url = yzAppFullUrl('goods/' . $item['id']);
//                if (app('plugins')->isEnabled('store-cashier')) {
//                    $store_goods = new \Yunshop\StoreCashier\common\models\StoreGoods();
//                    $store_id = $store_goods->where('goods_id', $item['id'])->value('store_id');
//                    if ($store_id) {
//                        $url = yzAppFullUrl("goods/{$item['id']}/o2o/{$store_id}");
//                    }
//                }
//                $is_course = (new VideoDemandCourseGoods())->isCourse($item['id']);
//                if ($is_course) {
//                    $url = yzAppFullUrl("member/coursedetail/{$item['id']}");
//                }

                return array_add($item, 'url', $url);
            });

            echo json_encode($goods);
            exit;
        }
    }

    public function getSmallMyLinkGoods()
    {
        if (!\YunShop::request()->kw) {
            $postData = file_get_contents('php://input', true);
            $obj = json_decode($postData);
            \YunShop::request()->kw = $obj->kw;
            //dd($obj->kw);
        }

        if (\YunShop::request()->kw) {
            $goods = \app\common\models\Goods::getGoodsByName(\YunShop::request()->kw);

            if (!$goods->isEmpty()) {
                $goods = set_medias($goods->toArray(), array('thumb', 'share_icon'));
            }
            $goods = collect($goods)->map(function ($item) {

                $url = '/pages/detail_v2/detail_v2?id='. $item['id'];

                return array_add($item, 'url', $url);
            });

            echo json_encode($goods);
            exit;
        }
    }

    public function SearchOrder()
    {//获取商品名称
        $keyword = request()->keyword;
        $pluginId = request()->plugin_id;

        if (empty($pluginId)) {
            $pluginId = 0;
        }
        $goods = Goods::getSearchOrder($keyword, $pluginId);
        return view('goods.query', [
            'goods' => $goods->toArray(),
        ])->render();
    }

    /**
     * 商品批量导入
     */
    public function import()
    {
        return view('goods.import')->render();
    }

    /**
     *  解压zip文件
     * @string $file  需要解压的文件的绝对路径
     * @string $destination 解压文件的绝对路径
     * @return bool
     *
     */
    private function unZipFile($file, $destination)
    {
        $zip = new \ZipArchive(); // 实例化对象
        if ($zip->open($file) !== true) {    //打开zip文档
            return false; //无法打开zip文件
        }
        $zip->extractTo($destination);//将压缩文件解压到指定的目录下
        $zip->close(); //关闭zip文档
        return ture;
    }

    //ajax 异步上传文件
    public function updateZip()
    {
        $file = request()->file('file');
        if (!$file) {
            return $this->errorJson('请传入正确参数.');
        }

        if ($file->isValid()) {
            // 获取文件相关信息
            $originalName = $file->getClientOriginalName(); // 文件原名
            $realPath = $file->getRealPath();   //临时文件的绝对路径
            $ext = $file->getClientOriginalExtension();
            $newOriginalName = md5($originalName . str_random(6)) . '.' . $ext;
            \Storage::disk('image')->put($newOriginalName, file_get_contents($realPath));
            if (config('app.framework') == 'platform') {
                $attachment = base_path() . '/static/upload/';
            } else {
                $attachment = $_SERVER['DOCUMENT_ROOT'] . '/attachment/image/';
            }
            if (is_dir($attachment)) {
                mkdir($attachment);
            }
            if ($this->unZipFile($attachment . $newOriginalName, $attachment) == true) {
                return $this->successJson('上传成功');
            } else {
                return $this->errorJson('解压失败');
            }
        }
    }


    /**
     * excel 商品导入
     * @return \Illuminate\Http\JsonResponse
     */
    public function a()
    {
        if (config('app.framework') == 'platform') {
            $attachment = 'static/upload/';
        } else {
            $attachment = 'attachment/';
        }
        $scheme = empty($_SERVER['HTTPS']) ? 'http://' : 'https://';
        $url = $scheme . $_SERVER['HTTP_HOST'];
        $url = $url . '/' . $attachment . 'image/';
        $data = request()->input('data');
        $i = 0;
        $goodsName = array_column($data, '商品名称');
        foreach ($data as $key => $value) {
            $goodsData[$i] = [
                'uniacid' => $value['公众号'] ?: 0,
                'display_order' => $value['排序'],
                'title' => $value['商品名称'],
                'brand_id' => $this->getBrandId(['uniacid' => $value['公众号'], 'brand' => $value['品牌']]),
                'type' => $value['商品类型'],
                'sku' => $value['商品单位'],
                'is_recommand' => $value['推荐'],
                'is_new' => $value['新上'],
                'is_hot' => $value['热卖'],
                'is_discount' => $value['促销'],
                'thumb' => $url . $value['商品图片'],
                'goods_sn' => $value['商品编号'],
                'product_sn' => $value['商品条码'],
                'price' => $value['商品现价'],
                'market_price' => $value['商品原价'],
                'cost_price' => $value['成本价'],
                'weight' => $value['重量'],
                'stock' => $value['库存'],
                'virtual_sales' => $value['虚拟销量'],
                'reduce_stock_method' => $value['拍下减库存'],
                'no_refund' => $value['不可退货退款'],
                'status' => $value['是否上架'],
                'content' => $value['商品描述']
            ];
            $goodsCategorys[$value['商品名称']] = [
                'title' => $value['商品名称'],
                'category1' => $value['商品分类一'],
                'category2' => $value['商品分类二'],
            ];
            $i++;
        }
        unset($data);
        unset($i);
        $result = Goods::insert($goodsData);
        unset($goodsData);
        $goodsId = Goods::select('id', 'uniacid', 'title')->whereIn('title', $goodsName)->get()->toArray();
        unset($goodsName);
        foreach ($goodsId as $k => $v) {
            if (isset($goodsCategorys[$v['title']])) {
                $goodsId[$k] = array_merge($v, $goodsCategorys[$v['title']]);
            }
            unset($k);
        }
        unset($v);
        $goodsCategory = array();
        foreach ($goodsId as $a => $b) {
            $temp = $this->getCategoryId([
                'uniacid' => $b['uniacid'],
                'category_name_1' => $b['category1'],
                'category_name_2' => $b['category2'],
            ]);
            $goodsCategory[$a] = [
                'goods_id' => $b['id'],
                'category_id' => $temp['category_id'],
                'category_ids' => $temp['category_ids'],
                'created_at' => $_SERVER['REQUEST_TIME'],
                'updated_at' => $_SERVER['REQUEST_TIME'],
            ];
            unset($temp);
            unset($a);
        }
        unset($b);
        $result = GoodsCategory::insert($goodsCategory);
        if ($result) {
            return $this->successJson('导入成功');
        }
    }

    /**
     *   //todo 通过数组下标查找,没有就添加，如果上传的excel里分类较多，需优化
     * @param $level
     * @param $uniacid
     * @param $name
     * @return mixed
     */
    private function getCategoryId($array)
    {
        if ($array['category_name_1'] == null and $array['category_name_2'] == null) {
            return [
                'category_id' => 0,
                'category_ids' => '',
            ];
        }
        if (is_null($this->list)) {
            $this->list = array_column(Category::select('id', 'name', 'uniacid', 'level')->where('plugin_id', 0)->get()->toArray(), null, 'name');
        }
        $result = array();
        if ($this->list[$array['category_name_1']]) {
            if ($this->list[$array['category_name_1']]['uniacid'] == $array['uniacid']) {
                $result['category_id_1'] = $this->list[$array['category_name_1']]['id'];
            } else {
                $result['category_id_1'] = $this->addCategory([
                    'uniacid' => $array['uniacid'],
                    'name' => $array['category_name_1'],
                    'level' => 1,
                    'plugin_id' => 0,
                    'is_home' => 1,
                    'parent_id' => 0
                ]);
            }
        } else {
            $result['category_id_1'] = $this->addCategory([
                'uniacid' => $array['uniacid'],
                'name' => $array['category_name_1'],
                'level' => 1,
                'plugin_id' => 0,
                'is_home' => 1,
                'parent_id' => 0
            ]);
        }

        //商品二级分类
        if ($this->list[$array['category_name_2']]) {
            if ($this->list[$array['category_name_2']]['uniacid'] == $array['uniacid']) {
                $result['category_id'] = $this->list[$array['category_name_2']]['id'];
                $result['category_ids'] = $result['category_id_1'] . ',' . $result['category_id'];
            } else {
                $result['category_id'] = $this->addCategory([
                    'uniacid' => $array['uniacid'],
                    'name' => $array['category_name_2'],
                    'level' => 2,
                    'plugin_id' => 0,
                    'is_home' => 1,
                    'parent_id' => $result['category_id_1']
                ]);
                $result['category_ids'] = $result['category_id_1'] . ',' . $result['category_id'];
            }
        } else {
            $result['category_id'] = $this->addCategory([
                'uniacid' => $array['uniacid'],
                'name' => $array['category_name_2'],
                'level' => 2,
                'plugin_id' => 0,
                'is_home' => 1,
                'parent_id' => $result['category_id_1']
            ]);
            $result['category_ids'] = $result['category_id_1'] . ',' . $result['category_id'];
        }
        if (!$result['category_ids']) {
            $result['category_ids'] = $result['category_id'];
        }
        unset($result['category_id_1']);
        return $result;
    }

    /**
     * 添加分类表
     * @param $array
     * @return int
     */
    private function addCategory($array)
    {
        $id = Category::insertGetId($array);
        $this->list = array_column(Category::select('id', 'name', 'uniacid', 'level')->where('plugin_id', 0)->get()->toArray(), null, 'name');
        return $id;
    }

    /**
     * 通过数组下标获取brand_id
     * @param $array
     * @return mixed
     */
    private function getBrandId($array)
    {
        if (is_null($this->brand)) {
            $this->brand = array_column(Brand::get()->toArray(), null, 'name');
        }
        if ($this->brand[$array['brand']]) {
            if ($this->brand[$array['brand']]['uniacid'] == $array['uniacid']) {
                return $this->brand[$array['brand']]['id'];
            } else {
                //todo 添加品牌
                return $this->addBrand([
                    'uniacid' => $array['uniacid'],
                    'name' => $array['brand'],
                    'alias' => '批量添加',
                    'logo' => '',
                    'desc' => '',
                    'created_at' => $_SERVER['REQUEST_TIME'],
                    'updated_at' => $_SERVER['REQUEST_TIME'],
                ]);
            }
        } else {
            return $this->addBrand([
                'uniacid' => $array['uniacid'],
                'name' => $array['brand'],
                'alias' => '',
                'logo' => '',
                'desc' => '',
                'created_at' => $_SERVER['REQUEST_TIME'],
                'updated_at' => $_SERVER['REQUEST_TIME'],
            ]);
        }
    }

    /**
     * 添加品牌
     * @param $array
     * @return int
     */
    private function addBrand($array)
    {
        $id = Brand::insertGetId($array);
        $this->brand = array_column(Brand::get()->toArray(), null, 'name');
        return $id;
    }

    /**
     * demo 下载
     */
    public function excelImport()
    {
        $exportData['0'] = ["公众号", "排序", '商品名称', '商品分类一', '商品分类二', '商品品牌', '商品类型', '商品单位',
            '商品属性', '商品图片', '商品编号', '商品条码', '商品现价', '商品原价', '成本价', '虚拟销量', '减库存方式', '不可退换货',
            '是否上架', '商品描述', '推荐', '新上', '热卖', '促销', '商品图片'
        ];

        \Excel::create('商品批量导入模板', function ($excel) use ($exportData) {
            $excel->setTitle('Office 2005 XLSX Document');
            $excel->setCreator('芸众商城');
            $excel->setLastModifiedBy("芸众商城");
            $excel->setSubject("Office 2005 XLSX Test Document");
            $excel->setDescription("Test document for Office 2005 XLSX, generated using PHP classes.");
            $excel->setKeywords("office 2005 openxml php");
            $excel->setCategory("report file");
            $excel->sheet('info', function ($sheet) use ($exportData) {
                $sheet->rows($exportData);
            });
        })->export('xls');
    }
}
